// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file proto/controls/controls.proto (package controls, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateControlsRequest, CreateControlsResponse, DeleteControlsRequest, DeleteControlsResponse, GetControlsRequest, GetControlsResponse, UpdateControlsRequest, UpdateControlsResponse } from "./controls_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The Controls service definition.
 *
 * @generated from service controls.ControlsService
 */
export const ControlsService = {
  typeName: "controls.ControlsService",
  methods: {
    /**
     * @generated from rpc controls.ControlsService.CreateControls
     */
    createControls: {
      name: "CreateControls",
      I: CreateControlsRequest,
      O: CreateControlsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc controls.ControlsService.GetControls
     */
    getControls: {
      name: "GetControls",
      I: GetControlsRequest,
      O: GetControlsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc controls.ControlsService.UpdateControls
     */
    updateControls: {
      name: "UpdateControls",
      I: UpdateControlsRequest,
      O: UpdateControlsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc controls.ControlsService.DeleteControls
     */
    deleteControls: {
      name: "DeleteControls",
      I: DeleteControlsRequest,
      O: DeleteControlsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

