// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file proto/sensors/sensors.proto (package sensors, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateSensorsRequest, CreateSensorsResponse, DeleteSensorsRequest, DeleteSensorsResponse, GetSensorsRequest, GetSensorsResponse, UpdateSensorsRequest, UpdateSensorsResponse } from "./sensors_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The Sensors service definition.
 *
 * @generated from service sensors.SensorsService
 */
export const SensorsService = {
  typeName: "sensors.SensorsService",
  methods: {
    /**
     * @generated from rpc sensors.SensorsService.CreateSensors
     */
    createSensors: {
      name: "CreateSensors",
      I: CreateSensorsRequest,
      O: CreateSensorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sensors.SensorsService.GetSensors
     */
    getSensors: {
      name: "GetSensors",
      I: GetSensorsRequest,
      O: GetSensorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sensors.SensorsService.UpdateSensors
     */
    updateSensors: {
      name: "UpdateSensors",
      I: UpdateSensorsRequest,
      O: UpdateSensorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sensors.SensorsService.DeleteSensors
     */
    deleteSensors: {
      name: "DeleteSensors",
      I: DeleteSensorsRequest,
      O: DeleteSensorsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

