models:
  - name: User
    fields:
      - name: id
        type: int32
        primary_key: true
        auto_increment: true
      - name: username
        type: string
      - name: email
        type: string
      - name: password
        type: string
