models:
  - name: Product
    fields:
      - name: id
        type: int32
        primary_key: true
        auto_increment: true
      - name: name
        type: string
      - name: amount
        type: int32
      - name: description
        type: string