models:
  - name: Controls
    fields:
      - name: id
        type: int32
        primary_key: true
        auto_increment: true
      - name: forward
        type: string
      - name: backward
        type: string
      - name: left
        type: string
      - name: right
        type: string
      - name: speed
        type: int32
  - name: Sensors
    fields:
      - name: id
        type: int32
        primary_key: true
        auto_increment: true
      - name: temperature
        type: int32
      - name: humidity
        type: int32
      - name: distance
        type: int32
      - name: light
        type: int32
      - name: sound
        type: int32